### ISSUE TITLE
Pull actual tweets from Twitter

### ISSUE THREAD

**Issue by edogdu** [edogdu/covid19#1]
Hydrate all tweets in USC datasets.

**Comment by thuynh3-minh** [comment]
https://medium.com/on-archivy/on-forgetting-e01a2b95272
I just read this paper. I think the tweets that are not collected are
deleted. hope it could explain something

**Comment by edogdu** [comment]
Not quite. Our problem is not the deleted tweets. In my case when I ran the hydrate.py, it stopped at some point, and did not continue with the rest of the tweets. It should skip the tweets that are deleted, but should continue downloading the remaining tweets.

**Comment by edogdu** [comment]
Minh, how is this going? Any updates? Let's do a virtual meeting when you are free...

**Comment by thuynh3-minh** [comment]
Hello dr Dogdu, good to hear from you. I can come to your office next
Monday or we can meet online Monday afternoon. Sorry for not doing any
updates. I am taking a data course in coursera because I think I should
know about the basics first.

Have a great weekend!

**Comment by thuynh3-minh** [comment]
update: 
Hydrate successfully using Hydrator [https://github.com/DocNow/hydrator](url)
Problem found on Monday, 31st Aug: Some retweets' full text is truncated. [https://github.com/DocNow/hydrator/issues/26] Full text is displayed at the end of the tweet so it is not really a problem. However, Huy wanted the full text to be consistent.
**Solved**: By using another tool to hydrate, that is twarc [https://github.com/DocNow/twarc](url). 
Steps: install with twitter dev account, open Window powershell and type "twarc hydrate filename.txt > filename.jsonl". It seems to be a little bit faster, too.
